### ISSUE TITLE
Empty response at `/api/stories/all`

### ISSUE THREAD

**Issue by rajdeepbharati** [scorelab/fact-Bounty#24]
I'm getting an empty array json response at this endpoint: `http://localhost:8080/api/stories/all`.
I have connected MongoDB and imported the dump in my database. Also set up the config.

**Comment by Tushar19varshney** [comment]
Hey @rajdeepbharati,
As your API endpoint port is 8080. So did you made a `.env` file and mentioned the port in it, because default port is 7000. If yes, then check if it is happening for all API because I have tested it and it was working fine.

**Comment by rajdeepbharati** [comment]
@Tushar19varshney yes, I have specified it

**Comment by rajdeepbharati** [comment]
I am getting this traceback in `http://localhost:8080/api/users/register` and `http://localhost:8080/api/users/login`:

```
NotFoundError: Not Found
    at /Users/rajdeep/fact-Bounty/fact-bounty-server/app.js:38:7
    at Layer.handle [as handle_request] (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:317:13)
    at /Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:275:10)
    at /Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:635:15
    at next (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:317:13)
    at /Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/express/lib/router/index.js:275:10)
    at initialize (/Users/rajdeep/fact-Bounty/fact-bounty-server/node_modules/passport/lib/middleware/initialize.js:53:5)
```

**Comment by Tushar19varshney** [comment]
> @Tushar19varshney yes, I have specified it

What about other API's, Are they working fine?

**Comment by rajdeepbharati** [comment]
The stories api is sending an empty array and a 304 response code:
![screenshot 2019-02-18 at 10 20 47 pm](https://user-images.githubusercontent.com/30660439/52965714-838dd980-33cb-11e9-95b5-2783836a9ec0.png)

**Comment by Tushar19varshney** [comment]
`NotFoundError: Not Found` occurs when you call the wrong route.
Check your `index.js` file in the `routes` folder

**Comment by Anmolbansal1** [comment]
Are you running on development environment??

**Comment by rajdeepbharati** [comment]
Yup

**Comment by Anmolbansal1** [comment]
Please try on production environment and reply whether there is the same or not

**Comment by Anmolbansal1** [comment]
> Yup.
> Maybe I've messed up the mongodb collection name?
> I have named the collections as `Story` and `User`

Yup there is the problem

**Comment by Anmolbansal1** [comment]
@rajdeepbharati is it working perfect now??

**Comment by rajdeepbharati** [comment]
Yes, the stories endpoint is working and I'm getting the response.
But the `/api/users/login` and `/api/users/register` isn't.
Should I create another issue for that?

**Comment by Anmolbansal1** [comment]
@rajdeepbharati login and register routes are also working, have you renamed the collection correctly as users??

**Comment by rajdeepbharati** [comment]
yes

**Comment by Anmolbansal1** [comment]
@rajdeepbharati I have just checked the users endpoints and both are working correctly

**Comment by Anmolbansal1** [comment]
Please send the request you are sending and response you are getting

**Comment by Pradip-001** [comment]
@Anmolbansal1 , is it responding with password incorrect?

**Comment by Anmolbansal1** [comment]
![screenshot from 2019-02-18 23-26-16](https://user-images.githubusercontent.com/39100247/52968933-c7391100-33d4-11e9-85e5-a352d7a6030f.png)
No @Pradip-001 , it is responding correctly

**Comment by Pradip-001** [comment]
No, i think i know whats the problem, i need decrypted password

**Comment by Pradip-001** [comment]
i was passing the hashed password

**Comment by Anmolbansal1** [comment]
Ohk @Pradip-001 nice to know your issue has been resolved.
What about your issue @rajdeepbharati ??

**Comment by Pradip-001** [comment]
Thanks, @Anmolbansal1

**Comment by rajdeepbharati** [comment]
@Anmolbansal1 thanks, now it's working fine
