### ISSUE TITLE
Web Crawlers not working

### ISSUE THREAD

**Issue by Anmolbansal1** [scorelab/fact-Bounty#335]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

On running - `scrapy crawl am -o out.csv` 
It should put all data crawled to out.csv file in project folder.

# Current Behavior

Current data output - 
```'data': [{'date': None,
 'image_url': None,
 'newsInDetails': '',
 'news_headline': '\n'
                  '\t  \t\tපරිසරය දූෂණය කරන නිතීවීරෝධී ලී මෝලක් නිසා උකුවෙල '
                  'කැළඹෙයි\t  \t',
 'news_link': '/local-news/item/43055-2019-05-28-05-54-38'},
```
Also it is not able to follow link to next page. 
```
Traceback (most recent call last):
  File "/home/anmol/Desktop/fact-bounty/Crawlers/venv/lib/python3.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/anmol/Desktop/fact-bounty/Crawlers/venv/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/anmol/Desktop/fact-bounty/Crawlers/venv/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/anmol/Desktop/fact-bounty/Crawlers/venv/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/anmol/Desktop/fact-bounty/Crawlers/venv/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/anmol/Desktop/fact-bounty/Crawlers/news_sites/spiders/am.py", line 40, in parse
    next_link = "http://am.lk" + next_link

```

## Context

A similar problem exists for most of the spiders. Currently, there are 30 spiders in the project and all of them need to be analyzed.

**Comment by Anmolbansal1** [comment]
I will be tracking my progress on this issue with document - https://docs.google.com/document/d/1TyVrDvRCiTIEdtvN-uKSmKoKp0QFUZzxKwecL1AvIK0/edit?usp=sharing
